name: Test pre-commit and post-push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: start
        uses: actions/checkout@v4
      - name: download requirements
        run: sudo apt install cmake gcc libgtest-dev -y 
      - name: build
        run: mkdir build && cmake . -B ./build
      - name: run make
        run: make --directory=build
      - name: tests
        run: ./build/tests/tests
        
