name: Test pre-commit and post-push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env: 
  workdir: ./

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download requirements
        run: sudo apt install cmake gcc libgtest-dev -y 

      - name: Build project
        run: ./build.sh

      - name: Run tests
        run: ctest --test-dir ./build
